name: mycard
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Shadows Into Light
      fonts:
        - asset: fonts/ShadowsIntoLight-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 600